# # # Project metadata
# sonar.projectKey=diffBugTest
# sonar.organization=org
 
# # # Source and binary directories
# sonar.sources=.
 
# # # SonarQube server
# sonar.host.url=http://localhost:9000
# sonar.login=squ_8beab9cf62aae4ec2c887fa3f69af94661df5e70
#  license.secured=Q2hlY2tzdW06IFYzZDRkNTQyNWE0ODZhNzYyZGE0MTZjMGNiZWYxYzA0YWIKT3JnYW5pc2F0aW9uOiBDb2RlU2NhbgpTZXJ2ZXI6ICoKUHJvZHVjdDogc2YKVHlwZTogRVZBTFVBVElPTgpMaWNlbnNlU2VydmVyOiBodHRwczovL2xpY2Vuc2UuY29kZS1zY2FuLmNvbS9pbmRleC5waHAvYXBpL2FkZFByb2plY3Q/bGlkPTMzNDIzMjQKRXhwaXJhdGlvbjogMjAyOC0wNS0wNgpMb29wYmFjazogdHJ1ZQ==
#  sonar.pullrequest.key=23
#  sonar.pullrequest.branch=dhanushterala1509-patch-25
#  sonar.pullrequest.base=main


# # Required project identifiers
# sonar.projectKey=dhanushterala1509_switch-test
# sonar.organization=dhanushterala1509

# # SonarCloud server
# sonar.host.url=https://sonarcloud.io

# # Source code location
# sonar.sources=.

# # Encoding
# sonar.sourceEncoding=UTF-8

# # Organization and project keys are displayed in the right sidebar of the project homepage
# sonar.organization=dhanushterala1509
# sonar.projectKey=dhanushterala1509_testhtml
# sonar.host.url=https://sonarcloud.io
# sonar.token=ef33ea248a94ca0493cde7fc986625892d77bbb0
# sonar.pullrequest.key=5
# sonar.pullrequest.branch=dhanushterala1509-patch-7
# sonar.pullrequest.base=main
# sonar.verbose=true

# sonar.organization=githubactionsorg
# sonar.projectKey=githubactionsorg_githubactionsapp
# sonar.host.url=https://sonarcloud.io
# # sonar.pullrequest.key=5
# # sonar.pullrequest.branch=dhanushterala1509-patch-7
# # sonar.pullrequest.base=main


sonar.projectKey=githubactionsorg_githubapp
sonar.organization=githubactionsorg
sonar.verbose=true
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.sourceEncoding=UTF-8

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=githubActionsApp
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
